// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessageHistory(arg1, arg2) {
  return window['go']['main']['App']['GetMessageHistory'](arg1, arg2);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function SavePeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePeer'](arg1, arg2, arg3);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}
