// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function BroadcastMessage(arg1:string):Promise<void>;

export function GetActivePeers():Promise<Record<string, any>>;

export function GetLocalPeerInfo():Promise<Record<string, string>>;

export function GetMessageHistory(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetPeers():Promise<Array<database.Peer>>;

export function Greet(arg1:string):Promise<string>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SavePeer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetLocalName(arg1:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
